#!/bin/bash

# 🚀 Conectar GitHub con Railway
echo "🚀 CONECTANDO GITHUB CON RAILWAY"
echo "================================="
echo ""

# Configurar token de Railway
export RAILWAY_TOKEN="fd0c91b4-a5ee-413a-b919-621ce98ca9bd"

echo "📋 INSTRUCCIONES PARA CONECTAR GITHUB:"
echo ""
echo "1. 🌐 Ve a https://railway.app"
echo "2. ➕ Crea nuevo proyecto"
echo "3. 🔗 Selecciona 'Deploy from GitHub'"
echo "4. 📂 Busca: 'nov4-ix/son1kvers3-enhanced'"
echo "5. 🌿 Selecciona rama: 'main'"
echo "6. 📁 Directorio raíz: 'backend'"
echo "7. ⚙️ Configura variables de entorno"
echo "8. 🚀 Deploy automático"
echo ""

echo "🔧 VARIABLES DE ENTORNO PARA RAILWAY:"
echo "====================================="
echo ""
echo "NODE_ENV=production"
echo "PYTHON_VERSION=3.12"
echo "PYTHONPATH=/app/backend"
echo "HOST=0.0.0.0"
echo "PORT=8000"
echo "JWT_SECRET_KEY=son1kvers3_enhanced_production_secret_key_2024_railway_secure"
echo "JWT_ALGORITHM=HS256"
echo "JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60"
echo "DATABASE_URL=sqlite:///./son1kvers3.db"
echo "CORS_ORIGINS=https://son1kvers3.com,https://www.son1kvers3.com,https://enhanced.son1kvers3.com,https://v2.son1kvers3.com,https://son1kvers3-enhanced-9763d5l68-son1kvers3s-projects-c805d053.vercel.app,http://localhost:3000,http://127.0.0.1:3000"
echo "ALLOWED_HOSTS=son1kvers3.com,www.son1kvers3.com,enhanced.son1kvers3.com,v2.son1kvers3.com,backend-api.son1kvers3.com,server.son1kvers3.com,app.son1kvers3.com,son1kvers3-enhanced-9763d5l68-son1kvers3s-projects-c805d053.vercel.app,localhost,127.0.0.1"
echo "UPLOAD_DIR=./uploads/"
echo "OUTPUT_DIR=./output/"
echo "LOGS_DIR=./logs/"
echo "DEBUG=false"
echo "HEALTH_CHECK_ENABLED=true"
echo "METRICS_ENABLED=true"
echo "RAILWAY_ENVIRONMENT=production"
echo ""

echo "🚀 COMANDO DE INICIO:"
echo "cd backend && python3 -m uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""

echo "📋 CONFIGURACIÓN ADICIONAL:"
echo "=========================="
echo ""
echo "🔧 Build Command: pip install -r backend/requirements-simple.txt"
echo "🌐 Health Check: /health"
echo "⏱️ Timeout: 100 segundos"
echo "🔄 Restart Policy: ON_FAILURE"
echo "🔁 Max Retries: 3"
echo ""

echo "✅ ¡GitHub conectado y listo para Railway!"
echo ""
echo "🔗 ENLACES:"
echo "  🌐 Railway: https://railway.app"
echo "  📦 GitHub: https://github.com/nov4-ix/son1kvers3-enhanced"
echo "  📁 Backend: https://github.com/nov4-ix/son1kvers3-enhanced/tree/main/backend"
